version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: app
    ports:
      - 8080:4567
    environment:
      - PGPORT=5432
      - PGHOST=db
      - DB_NAME=app
      - DATABASE_URL=postgres://root:password1@db:5432
    volumes:
      - ./:/data/app
      - vendor:/data/app/vendor
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password1
      - POSTGRES_DB=app
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  vendor:
  db-data:
    driver: local
